services:
  ry-mysql:
    # 增加以下配置确保编码正确
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #image: harbor.host3/ruoyi/ry-mysql:${TAG:-latest}
    image: ry-mysql
    container_name: ry-mysql  # 明确容器名称
    restart: unless-stopped  # 自动重启策略
    environment:
      MYSQL_ROOT_PASSWORD: jytc$123
      MYSQL_DATABASE: ry
      MYSQL_USER: xbdzc
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化
#      - ./mysql/conf:/etc/mysql/conf.d  # 挂载自定义配置
    networks:
      - ry-network
    ports:
      - "3306:3306"
    healthcheck:  # 健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:  # 资源限制
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  ry-tomcat:
    image: harbor.host3/ruoyi/ry-tomcat:${TAG:-latest}
    #image: ry-tomcat
    container_name: ry-tomcat
    restart: always  # 强制始终重启
    depends_on:
      ry-mysql:
        condition: service_healthy  # 依赖 MySQL 健康状态
    environment:
      MYSQL_HOST: ry-mysql  # 使用服务名直接通信
      DB_USER: xbdzc
      DB_PASSWORD: 123456
      CATALINA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=12345 -Dcom.sun.management.jmxremote.rmi.port=12346 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=192.168.0.221 -javaagent:/jmx/jmx_prometheus_javaagent-1.3.0.jar=9404:/jmx/jmx-config.yml"
    volumes:
      - tomcat_logs:/opt/tomcat/logs  # 日志持久化
#      - ./apps:/opt/tomcat/webapps  # 挂载外部应用目录（可选）
      - ./jmx-config.yml:/jmx/jmx-config.yml  # 挂载配置文件
      - ./jmx_prometheus_javaagent-1.3.0.jar:/jmx/jmx_prometheus_javaagent-1.3.0.jar  # 挂载 Agent
    networks:
      - ry-network
    ports:
      - "80:80"
      - "9404:9404"  # 新增：暴露 JMX Exporter 的 HTTP 端口
    logging:  # 日志配置
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data: # 声明命名卷（自动管理位置）
  tomcat_logs:

networks:
  ry-network:  # 自定义网络
    driver: bridge
