# roles/mirror_config/tasks/main.yml
- name: 创建 Docker 配置目录
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: 配置镜像加速
  template:
    src: daemon.json.j2      # 模板路径：roles/mirror_config/templates/
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker