- name: 配置 DNS（模板方式）
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: "0644"
  when: manage_dns_config | bool
  notify: restart systemd-resolved

- name: 更新 resolv.conf 软链接
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  when: manage_dns_config | bool
  notify: restart systemd-resolved
